language: python
python:
  - "2.7"
env:
  - DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

install:
  - chmod ugo+x ./bench
  - ./bench setup docker
  - ./bench init frappe-bench
  - ./bench new-site site1.local
  - ./bench -c root "echo 127.0.0.1   site1.local >> /etc/hosts"
  - sudo su -c 'echo 127.0.0.1   site1.local >> /etc/hosts'
  - pip install --upgrade virtualenv
  - virtualenv -p python3 testenv
  - source testenv/bin/activate
  - pip install requests

script:
  - docker-compose ps | grep -i frappe
  - docker-compose ps | grep -i redis-cache
  - docker-compose ps | grep -i redis-queue
  - docker-compose ps | grep -i redis-socketio
  - docker-compose ps | grep -i mariadb
  - python test.py
  - docker-compose stop
