language: python
python:
  - "2.7"
env:
  - DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d
  - docker exec -it -u root frappe bash -c "cd /home/frappe && chown -R frappe:frappe ./*"
  - docker exec -i frappe bash -c "cd .. && bench init frappe-bench --skip-bench-mkdir --skip-redis-config-generation && cd frappe-bench"
  - docker exec -i frappe bash -c "mv Procfile_docker Procfile && mv sites/common_site_config_docker.json sites/common_site_config.json"
  - docker exec -i frappe bash -c "bench new-site site1.local"
  - docker exec -i -u root frappe bash -c "echo 127.0.0.1   site1.local >> /etc/hosts"
  - sudo su -c 'echo 127.0.0.1   site1.local >> /etc/hosts'
  - pip install --upgrade virtualenv
  - virtualenv -p python3 testenv
  - source testenv/bin/activate
  - pip install requests

script:
  - docker-compose ps | grep -i frappe
  - docker-compose ps | grep -i redis-cache
  - docker-compose ps | grep -i redis-queue
  - docker-compose ps | grep -i redis-socketio
  - docker-compose ps | grep -i mariadb
  - python test.py
  - docker-compose stop
