version: '2'
services:
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306" #mariadb-port
    container_name: mariadb

  redis-cache:
    image: redis:alpine
    container_name: redis-cache

  redis-queue:
    image: redis:alpine
    container_name: redis-queue

  redis-socketio:
    image: redis:alpine
    container_name: redis-socketio

  frappe:
    volumes:
      - ./frappe-bench:/home/frappe/frappe-bench
      - ./redis-conf/redis_cache.conf:/home/frappe/frappe-bench/config/redis_cache.conf
      - ./redis-conf/redis_queue.conf:/home/frappe/frappe-bench/config/redis_queue.conf
      - ./redis-conf/redis_socketio.conf:/home/frappe/frappe-bench/config/redis_socketio.conf
    build: .
    ports:
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    container_name: frappe
