name: Develop build

on:
  pull_request:
    branches:
      - main
    paths:
      - build/nginx/**
      - build/socketio/**
      - build/worker/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env

  schedule:
    # Every day at 12:00 pm
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build:
    name: Frappe and ERPNext
    uses: vrslev/frappe_docker/.github/workflows/docker-build-push.yml@beautify
    with:
      repo: erpnext
      version: develop
      push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
