name: Deploy Traefik and MariaDB

# on:
#   workflow_call:
on:
  workflow_dispatch:
  workflow_call:
# on:
#   workflow_run:
#     workflows: ["Master Workflow"]
#     types:
#       - completed

jobs:
  deploy:
    runs-on: 
      - self-hosted
      # - label-1
      # - ubuntu-latest

    steps:
      - name: checkout Script content
        uses: actions/checkout@v2 # checkout the repository content
## if the docker not install then using this script 
      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' # install the python version needed

      # - name: install dependicese
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install PyGithub
      # - name: fintechsys/docker_compose.py # run main.py
      #   env:
      #     SOME_SECRET: ${{ secrets.SOME_SECRET }}
      #   run: python fintechsys/docker_compose.py

      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Set up Docker Compose
      #   run: |
      #     sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #     sudo chmod +x /usr/local/bin/docker-compose

      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Set up Docker
      #   uses: actions/setup-docker@v4
    #   with:
    #     dockerfile: Dockerfile  # Path to your Dockerfile if you have one

      - name: Create directory
        run: |
          mkdir ~/gitops

      # - name: Create traefik.env file
      #   run: |
      #     echo 'TRAEFIK_DOMAIN=${{ vars.TRAEFIK_DOMAIN }}' > ~/gitops/traefik.env
      #     echo 'EMAIL=f.alfalahi@fintechsys.net' >> ~/gitops/traefik.env
      #     echo 'HASHED_PASSWORD='$(openssl passwd -apr1 ${{ vars.TRAEFIK_PASSWORD }} | sed 's/\$/\\\$/g') >> ~/gitops/traefik.env
  
      # - name: Docker Compose up for Traefik
      #   run: |
      #    docker-compose --project-name traefik \
      #     --env-file ~/gitops/traefik.env \
      #     -f overrides/compose.traefik.yaml \
      #     -f overrides/compose.traefik-ssl.yaml up -d
  
      - name: Create mariadb.env file
        run: echo "DB_PASSWORD=${{ vars.MARIADB_PASSWORD }}" > ~/gitops/mariadb.env
  
      - name: Deploy MariaDB container
        run: |
         docker-compose --project-name mariadb --env-file ~/gitops/mariadb.env -f overrides/compose.mariadb-shared.yaml up -d
